'use client';
import { FormEvent, useRef, useState } from "react";
import styles from "./page.module.css";
import Image from "next/image";

const REQUEST_TIMEOUT_MS = 10_000;

export default function Page() {

    const [userId, setUserId] = useState("");
    const [advertisingId, setAdvertisingId] = useState("");
    const [emailAddress, setEmailAddress] = useState("");
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const submissionInProgress = useRef(false);

    async function onSubmit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();

        if (submissionInProgress.current) {
            return;
        }

        submissionInProgress.current = true;
        setIsSubmitting(true);
        setIsSubmitted(false);
        setErrorMessage(null);

        const data = {
            userId,
            advertisingId,
            emailAddress
        };
        const controller = new AbortController();
        const timeoutId = window.setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

        try {
            const response = await fetch('https://kqszy8n9t0.execute-api.eu-west-2.amazonaws.com/prod/deletion-requests', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
                signal: controller.signal,
            });

            if (!response.ok) {
                throw new Error(`Deletion request failed with status ${response.status}`);
            }

            setIsSubmitted(true);
            setUserId("");
            setAdvertisingId("");
            setEmailAddress("");
        } catch (error) {
            const requestTimedOut = error instanceof DOMException && error.name === "AbortError";
            setErrorMessage(requestTimedOut
                ? "The request timed out. Please check your connection and try again."
                : "We could not submit your request. Please check your connection and try again."
            );
        } finally {
            window.clearTimeout(timeoutId);
            submissionInProgress.current = false;
            setIsSubmitting(false);
        }
    }
    return (
        <div className={styles.container}>
            <h1>Delete my Raft Rush data</h1>
            <p className={styles.text}>
                Raft Rush uses Unity Ads to display advertisements and Unity Leaderboards to store high scores. The following data types are collected:
            </p>
            <ol className={styles.numberedList}>
                <li>The alias you provide for display on the leaderboard</li>
                <li>An autogenerated username to track your high scores</li>
                <li>Identifiers such as your advertising Id and IP address for advertising purposes</li>
                <li>Your approximate location for advertising purposes</li>
            </ol>

            <p className={styles.text}>
                Your User Id can be found be pressing the user info button on the menu.
                <Image
                    src="/user-info-button.png"
                    alt="User Info Button"
                    width={24}
                    height={24}
                />
            </p>
            <p>
                For information on how to find your advertising ID, please see the following <a className={styles.links} href="https://support.google.com/googleplay/answer/3405269?hl=en">guide</a>.
            </p>
            <p>
                For more information on how Unity uses your data, please see their <a className={styles.links} href="https://unity3d.com/legal/privacy-policy">privacy policy</a>.
            </p>


            <p className={styles.text}>
                If you would like to delete this data from these services, please fill in the form below.
            </p>

            <form onSubmit={onSubmit} aria-busy={isSubmitting}>
                <ul className={styles.formWrapper}>
                    <li className={styles.formRow}>
                        <label htmlFor="email">Email*</label>
                        <input type="email" id="emailAddress" value={emailAddress} onChange={(e) => setEmailAddress(e.target.value)} required />
                    </li>
                    <li className={styles.formRow}>
                        <label htmlFor="userid">User Id*</label>
                        <input type="text" id="userId" value={userId} onChange={(e) => setUserId(e.target.value)} required />
                    </li>
                    <li className={styles.formRow}>
                        <label htmlFor="advertising">Advertising Id</label>
                        <input type="text" id="advertisingId" value={advertisingId} onChange={(e) => setAdvertisingId(e.target.value)} />
                    </li>
                    <li className={styles.formRow}>
                        <button type="submit" disabled={isSubmitting}>
                            {isSubmitting ? "Submitting..." : "Submit"}
                        </button>
                    </li>
                    {isSubmitted && <li className={styles.formRow} role="status">Your request has been submitted</li>}
                    {errorMessage && <li className={styles.formRow} role="alert">{errorMessage}</li>}
                </ul>
            </form>
        </div >
    );
}
