'use client';
import { FormEvent, useState } from "react";
import styles from "./page.module.css";
import Image from "next/image";

export default function Page() {

    const [userId, setUserId] = useState("");
    const [advertisingId, setAdvertisingId] = useState("");
    const [emailAddress, setEmailAddress] = useState("");
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [isError, setIsError] = useState(false);

    async function onSubmit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        const data = {
            userId,
            advertisingId,
            emailAddress
        };
        const response = await fetch('https://kqszy8n9t0.execute-api.eu-west-2.amazonaws.com/prod/deletion-requests', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data),
        });

        if (response.ok) {
            setIsSubmitted(true);
            setIsError(false);
            setUserId("");
            setAdvertisingId("");
            setEmailAddress("");
        } else {
            setIsError(true);
            setIsSubmitted(false);
        }


    }
    return (
        <div className={styles.container}>
            <h1>Delete my Raft Rush data</h1>
            <p className={styles.text}>
                Raft Rush uses Unity Ads to display advertisements and Unity Leaderboards to store high scores. The following data types are collected:
            </p>
            <ol className={styles.numberedList}>
                <li>The alias you provide for display on the leaderboard</li>
                <li>An autogenerated username to track your high scores</li>
                <li>Identifiers such as your advertising Id and IP address for advertising purposes</li>
                <li>Your approximate location for advertising purposes</li>
            </ol>

            <p className={styles.text}>
                Your User Id can be found be pressing the user info button on the menu.
                <Image
                    src="/user-info-button.png"
                    alt="User Info Button"
                    width={24}
                    height={24}
                />
            </p>
            <p>
                For information on how to find your advertising ID, please see the following <a className={styles.links} href="https://support.google.com/googleplay/answer/3405269?hl=en">guide</a>.
            </p>
            <p>
                For more information on how Unity uses your data, please see their <a className={styles.links} href="https://unity3d.com/legal/privacy-policy">privacy policy</a>.
            </p>


            <p className={styles.text}>
                If you would like to delete this data from these services, please fill in the form below.
            </p>

            <form onSubmit={onSubmit}>
                <ul className={styles.formWrapper}>
                    <li className={styles.formRow}>
                        <label htmlFor="email">Email*</label>
                        <input type="email" id="emailAddress" value={emailAddress} onChange={(e) => setEmailAddress(e.target.value)} required />
                    </li>
                    <li className={styles.formRow}>
                        <label htmlFor="userid">User Id*</label>
                        <input type="text" id="userId" value={userId} onChange={(e) => setUserId(e.target.value)} required />
                    </li>
                    <li className={styles.formRow}>
                        <label htmlFor="advertising">Advertising Id</label>
                        <input type="text" id="advertisingId" value={advertisingId} onChange={(e) => setAdvertisingId(e.target.value)} />
                    </li>
                    <li className={styles.formRow}>
                        <button type="submit">Submit</button>
                    </li>
                    {isSubmitted && <li className={styles.formRow}>Your request has been submitted</li>}
                    {isError && <li className={styles.formRow}>There was an error submitting your request</li>}
                </ul>
            </form>
        </div >
    );
}